# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-22 12:49
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='\u5206\u7c7b\u540d')),
            ],
            options={
                'verbose_name': '\u5546\u54c1\u5206\u7c7b',
                'verbose_name_plural': '\u5546\u54c1\u5206\u7c7b',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='\u4ea7\u54c1')),
                ('subTitle', models.CharField(max_length=500, verbose_name='\u5c0f\u6807\u9898')),
                ('orignalPrice', models.FloatField(verbose_name='\u539f\u59cb\u4ef7\u683c')),
                ('promoteprice', models.FloatField(verbose_name='\u4f18\u60e0\u4ef7\u683c')),
                ('stock', models.FloatField(verbose_name='\u5e93\u5b58')),
                ('createDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('saleCount', models.IntegerField(verbose_name='\u9500\u552e\u6570\u91cf')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Category', verbose_name='\u5206\u7c7b')),
            ],
            options={
                'verbose_name': '\u4ea7\u54c1\u8868',
                'verbose_name_plural': '\u4ea7\u54c1\u8868',
            },
        ),
        migrations.CreateModel(
            name='ProductDetailImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='image/default.png', upload_to='produceImage/Detail')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='\u6240\u5c5e\u5546\u54c1')),
            ],
            options={
                'verbose_name': '\u4ea7\u54c1\u8be6\u60c5\u56fe\u7247',
                'verbose_name_plural': '\u4ea7\u54c1\u8be6\u60c5\u56fe\u7247',
            },
        ),
        migrations.CreateModel(
            name='ProductSingleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='image/default.png', upload_to='produceImage/Single')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='\u6240\u5c5e\u5546\u54c1')),
            ],
            options={
                'verbose_name': '\u4ea7\u54c1\u6807\u9898\u56fe\u7247',
                'verbose_name_plural': '\u4ea7\u54c1\u6807\u9898\u56fe\u7247',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='\u5c5e\u6027')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Category', verbose_name='\u5206\u7c7b')),
            ],
            options={
                'verbose_name': '\u5c5e\u6027',
                'verbose_name_plural': '\u5c5e\u6027',
            },
        ),
        migrations.CreateModel(
            name='PropertyValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200, verbose_name='\u5c5e\u6027\u503c')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='\u6240\u5c5e\u5546\u54c1')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Property', verbose_name='\u5c5e\u6027\u540d')),
            ],
            options={
                'verbose_name': '\u5c5e\u6027\u503c',
                'verbose_name_plural': '\u5c5e\u6027\u503c',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='\u8bc4\u4ef7\u5185\u5bb9')),
                ('createDate', models.DateTimeField(default=datetime.datetime(2017, 5, 22, 12, 49, 3, 345000), verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='\u6240\u5c5e\u5546\u54c1')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u6240\u5c5e\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u4ea7\u54c1\u8bc4\u4ef7',
                'verbose_name_plural': '\u4ea7\u54c1\u8bc4\u4ef7',
            },
        ),
    ]
