# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-06 08:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u6240\u5c5e\u7528\u6237'),
        ),
        migrations.AddField(
            model_name='propertyvalue',
            name='Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='\u6240\u5c5e\u5546\u54c1'),
        ),
        migrations.AddField(
            model_name='propertyvalue',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Property', verbose_name='\u5c5e\u6027\u540d'),
        ),
        migrations.AddField(
            model_name='property',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Category', verbose_name='\u5206\u7c7b'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='\u6240\u5c5e\u5546\u54c1'),
        ),
        migrations.AddField(
            model_name='product',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Category', verbose_name='\u5206\u7c7b'),
        ),
    ]
