# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-13 13:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20170513_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='createData',
            new_name='createDate',
        ),
    ]
