# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-13 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20170513_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='Category',
            new_name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='saleCount',
            field=models.IntegerField(default=3, verbose_name='\u9500\u552e\u6570\u91cf'),
            preserve_default=False,
        ),
    ]
