# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-22 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(verbose_name='\u6536\u8d27\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='order',
            name='confirmDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u786e\u8ba4\u6536\u8d27\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='order',
            name='createDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u521b\u5efa\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliveryDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u53d1\u8d27\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u652f\u4ed8\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='order',
            name='userMessage',
            field=models.TextField(verbose_name='\u7528\u6237\u5907\u6ce8\u4fe1\u606f'),
        ),
    ]
