# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-20 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('waitPay', '\u7b49\u5f85\u652f\u4ed8'), ('waitDelivery', '\u7b49\u5f85\u53d1\u8d27'), ('waitConfirm', '\u7b49\u5f85\u6536\u8d27'), ('waitReview', '\u7b49\u5f85\u8bc4\u4ef7'), ('finish', '\u4ea4\u6613\u5b8c\u6210'), ('delete', '\u8ba2\u5355\u5220\u9664')], default='waitPay', max_length=100, verbose_name='\u8ba2\u5355\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operation.Order', verbose_name='\u8ba2\u5355'),
        ),
    ]
