# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-07 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='code',
            field=models.CharField(max_length=80, verbose_name='\u9a8c\u8bc1\u7801'),
        ),
    ]
